defaults:
  - _self_
  - data: her_labels.yaml
  - model: her_classifier.yaml
  - callbacks: default.yaml
  - logger: wandb.yaml
  - trainer: default.yaml
  - setup: default.yaml

# ckpt_path: hehehe
dryrun: false
